name: Debian Security

on:
  schedule:
    # nightly at 3:00
    - cron: "3 0 * * *"
  workflow_dispatch:

concurrency:
  group: debian-security
  cancel-in-progress: true

jobs:
  debian-security:
    name: Debian Security
    uses: "./.github/workflows/debian-metadata.yml"
    permissions:
      contents: write
      pull-requests: write
    with:
      repository: apt-repositories/debian
      DEBIAN_MIRROR: security.debian.org
      DEBIAN_ROOT: debian-security
      DEBIAN_ARCHITECTURE: amd64
      DEBIAN_RELEASE: ${{ matrix.DEBIAN_RELEASE }}
      DEBIAN_COMPONENT: ${{ matrix.DEBIAN_COMPONENT }}
    secrets:
      GH_ORG_TOKEN: ${{ secrets.GH_ORG_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        DEBIAN_RELEASE:
          - bookworm-security
          - bullseye-security
          - trixie-security
        DEBIAN_COMPONENT:
          - main
          - contrib
          - non-free
          - non-free-firmware
        exclude:
          - DEBIAN_RELEASE: bullseye-security
            DEBIAN_COMPONENT: non-free-firmware
