name: Debian Updates

on:
  schedule:
    # nightly at 3:00
    - cron: "3 0 * * *"
  workflow_dispatch:

concurrency:
  group: debian-updates
  cancel-in-progress: true

jobs:
  debian-updates:
    name: Debian Updates
    uses: ./.github/workflows/metadata.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      repository: apt-repositories/debian
      DEBIAN_MIRROR: ftp.us.debian.org
      DEBIAN_ROOT: debian
      DEBIAN_ARCHITECTURE: amd64
      DEBIAN_RELEASE: ${{ matrix.DEBIAN_RELEASE }}
      DEBIAN_COMPONENT: ${{ matrix.DEBIAN_COMPONENT }}
    secrets:
      GH_ORG_TOKEN: ${{ secrets.GH_ORG_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        DEBIAN_RELEASE:
          - bookworm-updates
          - bullseye-updates
          - buster-updates
          - trixie-updates
        DEBIAN_COMPONENT:
          - main
          - contrib
          - non-free
          - non-free-firmware
        exclude:
          - DEBIAN_RELEASE: bullseye-updates
            DEBIAN_COMPONENT: non-free-firmware
          - DEBIAN_RELEASE: buster-updates
            DEBIAN_COMPONENT: non-free-firmware
