name: Debian

on:
  schedule:
    # nightly at 4:00
    - cron: "4 0 * * *"
  workflow_dispatch:

concurrency:
  group: debian
  cancel-in-progress: true

jobs:
  debian:
    name: Debian
    uses: ./.github/workflows/metadata.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      branch: debian
      repository: apt-repositories/debian
      BASE_ID_ONLY: debian
    secrets:
      GH_ORG_TOKEN: ${{ secrets.GH_ORG_TOKEN }}
