name: Manage Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch:

concurrency: manage-labels

jobs:
  manage-labels:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: oliversalzburg/action-label-manager@24f166c093a7f3bcf8cd7b2ff4ce90cc0c21db9e # v0.0.12
        with:
          force: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
