name: Manage Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch:

concurrency: manage-labels

jobs:
  manage-labels:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: oliversalzburg/action-label-manager@7fd196e99abce5f869a8d1cbe2608df1713bee01 # v0.0.13
        with:
          force: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
