name: Manage Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch:

concurrency: manage-labels

jobs:
  manage-labels:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: oliversalzburg/action-label-manager@e8ee17d170db678551854d8436897c374e636872 # v2.0.1
        with:
          force: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
