name: Metadata

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      DEBIAN_MIRROR:
        required: true
        type: string
      DEBIAN_ROOT:
        required: true
        type: string
      DEBIAN_ARCHITECTURE:
        required: false
        type: string
        default: amd64
      DEBIAN_RELEASE:
        required: true
        type: string
      DEBIAN_COMPONENT:
        required: true
        type: string
      DEBIAN_OBSERVABLES:
        required: false
        type: string
        default: ""
    secrets:
      GH_ORG_TOKEN:
        required: true

jobs:
  metadata:
    name: Metadata
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    env:
      DEBIAN_MIRROR: ${{ inputs.DEBIAN_MIRROR }}
      DEBIAN_ROOT: ${{ inputs.DEBIAN_ROOT }}
      DEBIAN_ARCHITECTURE: ${{ inputs.DEBIAN_ARCHITECTURE }}
      DEBIAN_RELEASE: ${{ inputs.DEBIAN_RELEASE }}
      DEBIAN_COMPONENT: ${{ inputs.DEBIAN_COMPONENT }}

    steps:
      - name: Download raw subject
        run: wget https://${{ env.DEBIAN_MIRROR }}/${{ env.DEBIAN_ROOT }}/dists/${{ env.DEBIAN_RELEASE }}/${{ env.DEBIAN_COMPONENT }}/binary-amd64/Packages.xz

      - name: Store raw subject
        uses: actions/upload-artifact@v4
        with:
          name: Packages.xz
          path: Packages.xz

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          repository: ${{ inputs.repository }}
          token: ${{ secrets.GH_ORG_TOKEN }}

      - name: Select NodeJS version
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        env:
          # renovate: datasource=node-version depName=node versioning=node
          NODE_VERSION: "22.3.0"
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Update metadata
        id: metadata
        env:
          # renovate: datasource=npm depName=@apt-repositories/generator versioning=semver
          GENERATOR_VERSION: "0.0.41"
        run: |
          rm -rf apt/$DEBIAN_ROOT/$DEBIAN_RELEASE/$DEBIAN_COMPONENT || true

          set -o pipefail
          echo "log<<EOF" >> $GITHUB_OUTPUT
          npx --package @apt-repositories/generator@$GENERATOR_VERSION --command generate "apt/$DEBIAN_ROOT/$DEBIAN_RELEASE/$DEBIAN_COMPONENT" | tee --append $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          set +o pipefail

      - name: Make observable
        if: inputs.DEBIAN_OBSERVABLES
        id: observable
        env:
          DEBIAN_OBSERVABLES: ${{ inputs.DEBIAN_OBSERVABLES }}
          # renovate: datasource=npm depName=@apt-repositories/generator versioning=semver
          GENERATOR_VERSION: "0.0.32"
        run: |
          rm -rf apt/$DEBIAN_ROOT-observable/$DEBIAN_RELEASE/$DEBIAN_COMPONENT || true

          set -o pipefail
          echo "log<<EOF" >> $GITHUB_OUTPUT
          npx --package @apt-repositories/generator@$GENERATOR_VERSION --command observe "apt/$DEBIAN_ROOT-observable/$DEBIAN_RELEASE/$DEBIAN_COMPONENT" | tee --append $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          set +o pipefail

      - name: Create pull request
        id: pr
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        with:
          token: ${{ secrets.GH_ORG_TOKEN }}
          branch: "${{ env.DEBIAN_ROOT }}/${{ env.DEBIAN_RELEASE }}/${{ env.DEBIAN_COMPONENT }}"
          title: "chore(${{ env.DEBIAN_ROOT }}): ${{ env.DEBIAN_RELEASE }}/${{ env.DEBIAN_COMPONENT }}"
          labels: |
            metadata
            ${{ env.DEBIAN_RELEASE }}
          body: |
            ## Metadata Log
            ```shell
            ${{ steps.metadata.outputs.log }}
            ```

            ## Observable Log
            ```shell
            ${{ steps.observable.outcome != 'skipped' && steps.observable.outputs.log || 'skipped' }}
            ```
          commit-message: |
            chore(${{ env.DEBIAN_ROOT }}): Metadata update for ${{ env.DEBIAN_RELEASE }}/${{ env.DEBIAN_COMPONENT }}

            Generated at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Auto-merge pull request
        if: steps.pr.outputs.pull-request-number
        run: gh pr merge --merge --auto "${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GH_ORG_TOKEN }}
