name: Metadata

on:
  workflow_call:
    inputs:
      branch:
        description: The branch to put the changes for the PR on.
        required: true
        type: string
      repository:
        description: The name of the repository where we publish the metadata.
        required: true
        type: string
      baseIdOnly:
        description: Process only this base release ID.
        required: false
        type: string
      observeOnly:
        default: false
        description: Skip downloading metadata, and just produce observables from existing files.
        required: false
        type: boolean
    secrets:
      GH_ORG_TOKEN:
        required: true

env:
  # renovate: datasource=npm depName=@apt-repositories/generator versioning=semver
  GENERATOR_VERSION: "2.0.5"
  # renovate: datasource=node-version depName=node versioning=node
  NODE_VERSION: "22.14.0"
  NODE_OPTIONS: --enable-source-maps

jobs:
  metadata:
    name: Metadata
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    env:
      BASE_ID_ONLY: ${{ inputs.baseIdOnly }}
      OBSERVE_ONLY: ${{ inputs.observeOnly && '1' || '' }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: true
          repository: ${{ inputs.repository }}
          token: ${{ secrets.GH_ORG_TOKEN }}

      - name: Select NodeJS version
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Update metadata
        id: metadata
        run: |
          rm -rf apt || true

          set -o pipefail
          echo "log<<EOF" >> $GITHUB_OUTPUT
          2>&1 npx @apt-repositories/generator@$GENERATOR_VERSION | tee --append $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          set +o pipefail

      - name: Create pull request
        id: pr
        if: false
        uses: peter-evans/create-pull-request@dd2324fc52d5d43c699a5636bcf19fceaa70c284 # v7
        with:
          token: ${{ secrets.GH_ORG_TOKEN }}
          branch: ${{ inputs.branch }}
          title: "chore: Update Metadata from Snapshot"
          labels: |
            metadata
          body: |
            ## Metadata Log
            ```shell
            ${{ steps.metadata.outputs.log }}
            ```
          commit-message: |
            chore: Update Metadata from Snapshot

            Generated at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Auto-merge pull request
        if: false && steps.pr.outputs.pull-request-number
        run: gh pr merge --merge --auto "${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GH_ORG_TOKEN }}
