name: Metadata

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      DEBIAN_MIRROR:
        required: true
        type: string
      DEBIAN_ROOT:
        required: true
        type: string
      DEBIAN_ARCHITECTURE:
        required: false
        type: string
        default: amd64
      DEBIAN_RELEASE:
        required: true
        type: string
      DEBIAN_COMPONENT:
        required: true
        type: string
      DEBIAN_OBSERVABLES:
        required: false
        type: string
        default: ""
    secrets:
      GH_ORG_TOKEN:
        required: true

env:
  # renovate: datasource=npm depName=@apt-repositories/generator versioning=semver
  GENERATOR_VERSION: "1.0.1"
  # renovate: datasource=node-version depName=node versioning=node
  NODE_VERSION: "22.13.0"
  NODE_OPTIONS: --enable-source-maps

jobs:
  metadata:
    name: Metadata
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    env:
      DEBIAN_MIRROR: ${{ inputs.DEBIAN_MIRROR }}
      DEBIAN_ROOT: ${{ inputs.DEBIAN_ROOT }}
      DEBIAN_ARCHITECTURE: ${{ inputs.DEBIAN_ARCHITECTURE }}
      DEBIAN_RELEASE: ${{ inputs.DEBIAN_RELEASE }}
      DEBIAN_COMPONENT: ${{ inputs.DEBIAN_COMPONENT }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: ${{ inputs.repository }}
          token: ${{ secrets.GH_ORG_TOKEN }}

      - name: Select NodeJS version
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Update metadata
        id: metadata
        run: |
          rm -rf apt/$DEBIAN_ROOT/$DEBIAN_RELEASE/$DEBIAN_COMPONENT || true

          set -o pipefail
          echo "log<<EOF" >> $GITHUB_OUTPUT
          2>&1 npx --package @apt-repositories/generator@$GENERATOR_VERSION --command generate "apt/$DEBIAN_ROOT/$DEBIAN_RELEASE/$DEBIAN_COMPONENT" | tee --append $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          set +o pipefail

      - name: Make observable
        if: inputs.DEBIAN_OBSERVABLES
        id: observable
        env:
          DEBIAN_OBSERVABLES: ${{ inputs.DEBIAN_OBSERVABLES }}
          OUTPUT_DIRECTORY: "apt/${{ env.DEBIAN_ROOT }}-observable/${{ env.DEBIAN_RELEASE }}/${{ env.DEBIAN_COMPONENT }}"
        run: |
          rm -rf $OUTPUT_DIRECTORY || true

          set -o pipefail
          echo "log<<EOF" >> $GITHUB_OUTPUT
          2>&1 npx --package @apt-repositories/generator@$GENERATOR_VERSION --command observe | tee --append $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          set +o pipefail

      - name: Create pull request
        id: pr
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7
        with:
          token: ${{ secrets.GH_ORG_TOKEN }}
          branch: "${{ env.DEBIAN_ROOT }}/${{ env.DEBIAN_RELEASE }}/${{ env.DEBIAN_COMPONENT }}"
          title: "chore(${{ env.DEBIAN_ROOT }}): ${{ env.DEBIAN_RELEASE }}/${{ env.DEBIAN_COMPONENT }}"
          labels: |
            metadata
            ${{ env.DEBIAN_RELEASE }}
          body: |
            ## Metadata Log
            ```shell
            ${{ steps.metadata.outputs.log }}
            ```

            ## Observable Log
            ```shell
            ${{ steps.observable.outcome != 'skipped' && steps.observable.outputs.log || 'skipped' }}
            ```
          commit-message: |
            chore(${{ env.DEBIAN_ROOT }}): Metadata update for ${{ env.DEBIAN_RELEASE }}/${{ env.DEBIAN_COMPONENT }}

            Generated at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Auto-merge pull request
        if: steps.pr.outputs.pull-request-number
        run: gh pr merge --merge --auto "${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GH_ORG_TOKEN }}
