name: QA

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  qa:
    name: 🔹 QA
    uses: oliversalzburg/workflows/.github/workflows/qa-npm-package.yml@main
    permissions:
      contents: read
    with:
      has-mkdocs: false
