name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency: release

jobs:
  qa:
    name: 🔹 QA
    uses: oliversalzburg/workflows/.github/workflows/qa-npm-package.yml@main
    with:
      has-mkdocs: false

  release:
    name: 🔹 Publish
    needs: qa
    permissions:
      contents: write
      id-token: write
      packages: write
      pages: write
      pull-requests: read
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    uses: oliversalzburg/workflows/.github/workflows/publish-npm-package.yml@main
    with:
      has-github-pages: false
      has-mkdocs: false
      is-canary: false
      publish-script: |
        make
        npm version $RELEASE_VERSION
      wants-github-release: true
