name: Ubuntu Backports

on:
  schedule:
    # nightly at 3:00
    - cron: "3 0 * * *"
  workflow_dispatch:

concurrency:
  group: ubuntu-backports
  cancel-in-progress: true

jobs:
  ubuntu-backports:
    name: Ubuntu Backports
    uses: ./.github/workflows/metadata.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      repository: apt-repositories/ubuntu
      DEBIAN_MIRROR: archive.ubuntu.com
      DEBIAN_ROOT: ubuntu
      DEBIAN_ARCHITECTURE: amd64
      DEBIAN_RELEASE: ${{ matrix.DEBIAN_RELEASE }}
      DEBIAN_COMPONENT: ${{ matrix.DEBIAN_COMPONENT }}
    secrets:
      GH_ORG_TOKEN: ${{ secrets.GH_ORG_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        DEBIAN_RELEASE:
          - bionic-backports
          - focal-backports
          - jammy-backports
          - lunar-backports
          - mantic-backports
          - noble-backports
          - oracular-backports
          - trusty-backports
          - xenial-backports
        DEBIAN_COMPONENT:
          - main
          - multiverse
          - restricted
          - universe
