name: Ubuntu Security

on:
  schedule:
    # nightly at 3:00
    - cron: "3 0 * * *"
  workflow_dispatch:

concurrency:
  group: ubuntu-security
  cancel-in-progress: true

jobs:
  ubuntu-security:
    name: Ubuntu Security
    uses: ./.github/workflows/metadata.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      repository: apt-repositories/ubuntu
      DEBIAN_MIRROR: archive.ubuntu.com
      DEBIAN_ROOT: ubuntu
      DEBIAN_ARCHITECTURE: amd64
      DEBIAN_RELEASE: ${{ matrix.DEBIAN_RELEASE }}
      DEBIAN_COMPONENT: ${{ matrix.DEBIAN_COMPONENT }}
    secrets:
      GH_ORG_TOKEN: ${{ secrets.GH_ORG_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        DEBIAN_RELEASE:
          - bionic-security
          - focal-security
          - jammy-security
          - lunar-security
          - mantic-security
          - noble-security
          - oracular-security
          - trusty-security
          - xenial-security
        DEBIAN_COMPONENT:
          - main
          - multiverse
          - restricted
          - universe
