name: Ubuntu

on:
  schedule:
    # nightly at 4:00
    - cron: "4 0 * * *"
  workflow_dispatch:

concurrency:
  group: ubuntu
  cancel-in-progress: true

jobs:
  ubuntu:
    name: Ubuntu
    uses: ./.github/workflows/metadata.yml
    permissions:
      contents: write
      pull-requests: write
    with:
      branch: ubuntu
      repository: apt-repositories/ubuntu
      BASE_ID_ONLY: ubuntu
    secrets:
      GH_ORG_TOKEN: ${{ secrets.GH_ORG_TOKEN }}
